### ISSUE TITLE
BUG : Check and Apply .csv issue

### ISSUE THREAD

**Issue by Priso19** [WazeDev/WME-Advanced-Closures#3]
The script with .csv use doesn't work since the WME update from 03 July 2018.
The .csv file load correctly but the "Apply" and "Check segments" buttons does nothing

I use this script five day a week to upload csv night closures in France around Paris (we also need it for the cycling "Tour de France" starting Saturday) , thank you for your usefull help.

Mac OS 10.12.6 with Chrome version 67.0.3396.99

**Comment by crazycaveman** [comment]
This has already been fixed. Are you still having problems with the latest
version? If so, what errors are you seeing?

**Comment by Priso19** [comment]
Using version 2018.07.06.01

The .csv file load correctly and after a press on  'Check' or 'Apply' button nothing happens in the "parse CSV" function.

Message display "_0% Scanning segments. please wait..._" in the progress bar. The script doesn't seem to communicate with WME anymore...

Try on a PC another editor of the french closing team, same problem.

Are we talking about the same function in the script ? Using a .csv file to apply closures ?

<img width="235" alt="capture d ecran 2018-07-07 a 10 01 08" src="https://user-images.githubusercontent.com/17503388/42408417-c2433050-81cc-11e8-9829-ca43abbfb091.png">

Here an example of our .csv file : 
https://drive.google.com/open?id=1MVRTffemxHU2zKlX8M7EIY0D4fyvUfWR

The csv file structure has not changed, is it?

**Comment by crazycaveman** [comment]
OK, I see an issue with the check segments function, but applying the closures still works. But you're saying you can't apply closures using a CSV? If so, will you open the console and report any error messages. To report script console errors:
 - Press `F12` to open the console window
 - Then `CTRL+L` to clear it
 - Refresh WME
 - Report any red error messages

Error for checking segments:
![image](https://user-images.githubusercontent.com/5603960/42452148-4103fc18-8357-11e8-8a07-07c047c47393.png)

Applying closures via CSV:
![image](https://user-images.githubusercontent.com/5603960/42452310-a97df1f4-8357-11e8-9628-ddab1d4b551b.png)

**Comment by crazycaveman** [comment]
Just pushed an update to fix checking segments. Let me know if you see any errors after updating to 2018.07.09.01

**Comment by Priso19** [comment]
With 2018.07.09.01 version it's works perfectly ! 
Thank you very much.
